[package]
name = "nointerest"
version = "0.1.0"
authors = ["conorf50"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
